framework:
    messenger:
        # Vous pouvez conserver la configuration du transport des échecs
        failure_transport: failed

        transports:
            # Définissez ici votre transport échoué pour gérer les messages qui ne peuvent pas être traités
            failed: 'doctrine://default?queue_name=failed'

            # La configuration du transport `async` peut être commentée si vous ne souhaitez pas l'utiliser
            # async:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     ...

            # Le transport `sync` est défini mais commenté par défaut, décommentez-le si nécessaire
            sync: 'sync://'

        routing:
            # Les messages de type SendEmailMessage utiliseront désormais le transport `sync`
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
            # Si vous voulez que les autres messages utilisent toujours un transport asynchrone, laissez-les comme ils sont
            'Symfony\Component\Notifier\Message\ChatMessage': sync
            'Symfony\Component\Notifier\Message\SmsMessage': sync

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
